export const TOGGLE_ADD_MODA = 'TOGGLE_ADD_MODA'
export const TOGGLE_EDIT_MODA = 'TOGGLE_EDIT_MODA'
export const HIDE_FORMS = 'HIDE_FORMS'
export const NAVBAR_ACTIONS = 'NAVBAR_ACTIONS'
export const RESET_NAVBAR = 'RESET_NAVBAR'
export const NEW_MSG = 'NEW_MSG'
export const RESET_MSG = 'RESET_MSG'